-- Run once in the Supabase SQL editor, then seed.sql.
-- Event publishing is intentionally admin-only: the app has no event-creation UI.

create table public."User" (
  "UserID" bigint generated by default as identity not null,
  "UserProfilePhoto" text null,
  "UserFirstName" text null,
  "UserLastName" text null,
  "Username" text null,
  "Password" text null,
  "Email" text null,
  created_at timestamp with time zone not null default now(),
  constraint "User_pkey" primary key ("UserID")
) TABLESPACE pg_default;

create table public."Events" (
  "EventID" bigint generated by default as identity not null,
  "EventImage" timestamp with time zone not null default now(),
  "EventName" text null,
  "EventDescription" text null,
  "EventDate" date null,
  "EventTime" time without time zone null,
  "EventLocation" text null,
  "EventCatagory" text null,
  constraint "Events_pkey" primary key ("EventID")
) TABLESPACE pg_default;  

create table public."Bookmark" (
  "BookmarkID" bigint generated by default as identity not null,
  "UserID" bigint null,
  "EventID" bigint null,
  created_at timestamp with time zone not null default now(),
  constraint "Bookmark_pkey" primary key ("BookmarkID"),
  constraint "Bookmark_EventID_fkey" foreign KEY ("EventID") references "Events" ("EventID") on update CASCADE on delete set null,
  constraint "Bookmark_UserID_fkey" foreign KEY ("UserID") references "User" ("UserID") on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public."Friends" (
  "FriendshipID" bigint generated by default as identity not null,
  "FriendUserID" bigint not null,
  "UserID" bigint null,
  constraint "Friends_pkey" primary key ("FriendshipID"),
  constraint "Friends_FriendUserID_fkey" foreign KEY ("FriendUserID") references "User" ("UserID") on update CASCADE on delete CASCADE,
  constraint "Friends_UserID_fkey" foreign KEY ("UserID") references "User" ("UserID") on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public."RSVP" (
  "RSVPid" bigint generated by default as identity not null,
  "RSVPGoing" boolean null,
  created_at timestamp with time zone not null default now(),
  "UserID" bigint null,
  "EventID" bigint null,
  constraint "RSVP_pkey" primary key ("RSVPid"),
  constraint "RSVP_EventID_fkey" foreign KEY ("EventID") references "Events" ("EventID") on update CASCADE on delete CASCADE,
  constraint "RSVP_UserID_fkey" foreign KEY ("UserID") references "User" ("UserID") on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create function public.handle_new_user()
returns trigger as $$
begin
  insert into public."User" ("UserID", "Email")
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();